### ISSUE TITLE
Maybe use MutationObserver instead of interval

### ISSUE THREAD

**Issue by rikschennink** [diachedelic/vue-removed-hook-mixin#1]
Hi! We used your library as inspiration for fixing a similar issue in [Vue FilePond](https://github.com/pqina/vue-filepond/issues/82#issuecomment-491714576).

Instead of using `setInterval` you could use `MutationObserver` to determine the exact moment the container element has been removed from the DOM.

**Comment by diachedelic** [comment]
@rikschennink nice one, didn't know that API existed.  Published in v0.0.3

**Comment by diachedelic** [comment]
Oops, i mean v0.0.4
